### Send POST request with json body
POST http://localhost:8080/order
Content-Type: application/json

{
  "roadAddr": "서울특별시 마포구 성암로 301 (상암동)",
  "jibunAddr": "서울특별시 마포구 상암동 1595 한국지역정보개발원(KLID Tower)",
  "detailAddress": "1층",
  "products": [
    {
      "productId": 9999999,
      "quantity": 12
    },
    {
      "productId": 9999998,
      "quantity": 3
    }
  ]
}

> {%
    client.test("Validate", function () {
        client.assert(response.status === 200, "Response status: " + response.status);
        client.assert(response.contentType.mimeType === "application/json", "Expected 'application/json'");
    });

    client.log(response.body);
    client.global.set("id", response.body)
%}


### Send POST request with json body
GET http://localhost:8080/order/{{id}}
Content-Type: application/json

### Send POST request with json body
GET http://localhost:8080/order/10000002
Content-Type: application/json

### Send POST request with json body
GET http://localhost:8080/order?id=10000001&size=3
Content-Type: application/json

### Send POST request with json body
GET http://localhost:8080/order?size=3&page=4
Content-Type: application/json


### Send POST request with json body
PUT http://localhost:8080/order/10000002
Content-Type: application/json

{
  "roadAddr": "서울특별시 서초구 서초대로77길 17 (서초동)",
  "jibunAddr": "서울특별시 서초구 서초동 1307-21 BLOCK77",
  "detailAddr": "13층 1303호"
}

### Send POST request with json body
PUT http://localhost:8080/order/10000004
Content-Type: application/json

{
  "roadAddr": "서울특별시 서초구 서초대로77길 17 (서초동)",
  "jibunAddr": "서울특별시 서초구 서초동 1307-21 BLOCK77",
  "detailAddr": "13층 1303호"
}


### Send POST request with json body
DELETE http://localhost:8080/order/20000000
Content-Type: application/json

{
  "roadAddr": "서울특별시 서초구 서초대로77길 17 (서초동)",
  "jibunAddr": "서울특별시 서초구 서초동 1307-21 BLOCK77",
  "detailAddr": "13층 1303호"
}