### Send POST request with json body
POST http://localhost:8080/order
Content-Type: application/json

{
  "roadAddr": "서울특별시 마포구 성암로 301 (상암동)",
  "jibunAddr": "서울특별시 마포구 상암동 1595 한국지역정보개발원(KLID Tower)",
  "detailAddress": "1층",
  "products": [
    {
      "productId": 9999999,
      "quantity": 100
    },
    {
      "productId": 9999998,
      "quantity": 3
    }
  ]
}

> {%
    client.test("Validate", function () {
        client.assert(response.status === 200, "Response status: " + response.status);
        client.assert(response.contentType.mimeType === "application/json", "Expected 'application/json'");
    });

    client.log(response.body);
    client.global.set("id", response.body)
%}


### Send POST request with json body
GET http://localhost:8080/order/{{id}}
Content-Type: application/json
