spring:
  application:
    name: product
  datasource:
    url: jdbc:mysql://localhost:3306/product
    username: product
    password: product
    driver-class-name: com.mysql.cj.jdbc.Driver
server:
  port: 8081