spring:
  application:
    name: product
  datasource:
    url: jdbc:mysql://localhost:3306/product
    username: product
    password: product
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
#    generate-ddl: true
#    hibernate:
#      ddl-auto: create
    show-sql: true
#    defer-datasource-initialization: true
  sql:
    init:
      mode: always

server:
  port: 8081

logging:
  level:
    org.hibernate.orm.jdbc.bind: trace
    org:
      hibernate:
        type:
          descriptor:
            sql:
              BasicBinder: trace
    spring:
      jpa:
        properties:
          hibernate:
            type: trace