spring:
  application:
    name: product
  datasource:
    url: jdbc:mysql://localhost:3306/product
    username: product
    password: product
    driver-class-name: com.mysql.cj.jdbc.Driver
    #  jpa:
    #    generate-ddl: true
    #    hibernate:
    #      ddl-auto: create
  #    show-sql: true
  #    defer-datasource-initialization: true
  sql:
    init:
      mode: always
  kafka:
    producer:
      bootstrap-servers: localhost:9092
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      bootstrap-servers: localhost:9092
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      group-id: ${spring.application.name}
      properties:
        spring.json.trusted.packages: 'io.whatap.*'
      auto-offset-reset: earliest
      enable-auto-commit: false
      max-poll-records: 1
      isolation-level: read_committed
  redis:
    cluster:
      nodes: localhost:7001,localhost:7002,localhost:7003,localhost:7004,localhost:7005,localhost:7006
    lettuce:
      pool:
        enabled: true
        max-active: 20
        max-idle: 20
        min-idle: 20
    client-type: lettuce
server:
  port: 8081

logging:
  level:
    root: info
    com:
      zaxxer:
        hikari:
          pool:
            HikariPool: trace
    org.springframework.transaction: trace
#    org.hibernate.orm.jdbc.bind: trace
#    org:
#      hibernate:
#        type:
#          descriptor:
#            sql:
#              BasicBinder: trace
#    spring:
#      jpa:
#        properties:
#          hibernate:
#            type: trace