{
  "formatVersion": "1.1",
  "component": {
    "group": "io.whatap",
    "module": "order-event",
    "version": "0.0.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "order-event-0.0.1-SNAPSHOT.jar",
          "url": "order-event-0.0.1-SNAPSHOT.jar",
          "size": 4610,
          "sha512": "4fbdbcc565d1f4966027bf76adce397084965010cff76044ad60cc716cef6298b780963c8e582f13a55d75de18b8516400e949515b788646f0a8f1800aca82cd",
          "sha256": "cdedb1ce5a69e2c91335f7247400a15e62cd17436a71fd465214946611f1b90b",
          "sha1": "d96babfaeb85bda28245300afd44a681663257fc",
          "md5": "373517c755b69550272c7546aec9f6cb"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "order-event-0.0.1-SNAPSHOT.jar",
          "url": "order-event-0.0.1-SNAPSHOT.jar",
          "size": 4610,
          "sha512": "4fbdbcc565d1f4966027bf76adce397084965010cff76044ad60cc716cef6298b780963c8e582f13a55d75de18b8516400e949515b788646f0a8f1800aca82cd",
          "sha256": "cdedb1ce5a69e2c91335f7247400a15e62cd17436a71fd465214946611f1b90b",
          "sha1": "d96babfaeb85bda28245300afd44a681663257fc",
          "md5": "373517c755b69550272c7546aec9f6cb"
        }
      ]
    }
  ]
}
