spring:
  application:
    name: order
  datasource:
    url: jdbc:mysql://localhost:3306/order?sendFractionalSeconds=false
    username: order
    password: order
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
  sql:
    init:
      mode: always

  kafka:
    producer:
      bootstrap-servers: localhost:9092
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: all
      properties:
        enable.idempotence: true
      retries: 2147483647
  redis:
    cluster:
      nodes: localhost:7001,localhost:7002,localhost:7003,localhost:7004,localhost:7005,localhost:7006
    lettuce:
      pool:
        enabled: true
        max-active: 20
        max-idle: 20
        min-idle: 20
    client-type: lettuce
server:
  port: 8080

proxy:
  product: http://localhost:8081