spring:
  application:
    name: order
  datasource:
    url: jdbc:mysql://localhost:3306/order
    username: order
    password: order
    driver-class-name: com.mysql.cj.jdbc.Driver
server:
  port: 8080